name: Run All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Show Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        venv/bin/python3 -m pip install --upgrade pip
        venv/bin/python3 -m pip install -r requirements.txt

    - name: Run Task-1 tests
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        venv/bin/python3 step1test.py

    - name: Run Task-2 tests
      run: |
        ./step2run.sh cis-r1.pdf cis-r2.pdf

    - name: Run Task-3 tests
      run: |
        venv/bin/python3 step3test.py